name: Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read

jobs:
  pull_request:
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      working-directory: ./
      run-commit-lint: true
      run-build: true
      pre-test-script: |
        pipx install algokit
        algokit localnet start
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check docs are up to date
        shell: bash
        run: |
          npm ci --ignore-scripts
          npm run generate:code-docs
          git add -N .
          git diff --exit-code
