name: Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read

jobs:
  pull_request:
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@feature/semantic-release
    with:
      working-directory: ./
      run-commit-lint: true
      run-build: true
