name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@feature/semantic-release
    with:
      run-commit-lint: true
      run-build: true
      run-semantic-release: true
      test-script: ''
