name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      production_release:
        description: 'Production release?'
        required: true
        default: 'true'

concurrency: release

permissions:
  contents: write

jobs:
  ci:
    name: Continuous Integration
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@feature/semantic-release
    with:
      run-commit-lint: true
      run-pre-test: true
      pre-test-script: |
        pipx install algokit
        algokit localnet start

  build:
    name: Build
    uses: makerxstudio/shared-config/.github/workflows/node-build-zip.yml@feature/semantic-release
    needs: ci
    with:
      build-path: dist
      artifact-name: package

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package
          path: artifacts

      - name: Unzip package
        shell: bash
        run: |
          mkdir -p dist
          unzip -q "artifacts/package.zip" -d dist

      # semantic-release needs node 18
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 'Semantic beta release'
        if: ${{ inputs.production_release != 'true' }}
        working-directory: dist
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Semantic production release'
        if: ${{ inputs.production_release == 'true' }}
        working-directory: dist
        run: npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
